source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TFSlideControl_Example', :exclusive => true do
  pod "TFSlideControl", :path => "../"
end

target 'TFSlideControl_Tests', :exclusive => true do
  pod "TFSlideControl", :path => "../"

  
end
