source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TFSlideControl_Example' do
  pod "TFSlideControl", :path => "../"
end

target 'TFSlideControl_Tests' do
  pod "TFSlideControl", :path => "../"

  
end
